"""
Schemas package initialization.
"""

# Import all schemas for easy access
from app.schemas.auth import *
from app.schemas.auth import (
    Token,
    TokenPayload,
    User,
    UserBase,
    UserCreate,
    UserInDB,
    UserInDBBase,
    UserLogin,
    UserRegister,
    UserResponse,
    UserUpdate,
)
from app.schemas.client import (
    Client,
    ClientBase,
    ClientCreate,
    ClientInDBBase,
    ClientListResponse,
    ClientResponse,
    ClientUpdate,
)
from app.schemas.exercise import (
    Exercise,
    ExerciseBase,
    ExerciseCreate,
    ExerciseInDBBase,
    ExerciseListResponse,
    ExerciseResponse,
    ExerciseSearchQuery,
    ExerciseUpdate,
)
from app.schemas.meal import (
    Meal,
    MealBase,
    MealCreate,
    MealInDBBase,
    MealListResponse,
    MealPlan,
    MealPlanBase,
    MealPlanCreate,
    MealPlanInDBBase,
    MealPlanListResponse,
    MealPlanMealBase,
    MealPlanMealCreate,
    MealPlanMealResponse,
    MealPlanResponse,
    MealPlanUpdate,
    MealResponse,
    MealUpdate,
)
from app.schemas.payment import (
    Payment,
    PaymentBase,
    PaymentCreate,
    PaymentInDBBase,
    PaymentListResponse,
    PaymentMethodBase,
    PaymentMethodCreate,
    PaymentMethodResponse,
    PaymentResponse,
    PaymentUpdate,
    StripeWebhookPayload,
    Subscription,
    SubscriptionBase,
    SubscriptionCreate,
    SubscriptionInDBBase,
    SubscriptionResponse,
    SubscriptionUpdate,
)
from app.schemas.program import (
    Program,
    ProgramBase,
    ProgramCreate,
    ProgramExerciseBase,
    ProgramExerciseCreate,
    ProgramExerciseResponse,
    ProgramExerciseUpdate,
    ProgramInDBBase,
    ProgramListResponse,
    ProgramResponse,
    ProgramUpdate,
)
from app.schemas.progress import (
    ExerciseLogBase,
    ExerciseLogCreate,
    ExerciseLogResponse,
    Goal,
    GoalBase,
    GoalCreate,
    GoalInDBBase,
    GoalListResponse,
    GoalResponse,
    GoalUpdate,
    Progress,
    ProgressBase,
    ProgressCreate,
    ProgressInDBBase,
    ProgressListResponse,
    ProgressResponse,
    ProgressUpdate,
    WorkoutLog,
    WorkoutLogBase,
    WorkoutLogCreate,
    WorkoutLogInDBBase,
    WorkoutLogListResponse,
    WorkoutLogResponse,
    WorkoutLogUpdate,
)
from app.schemas.trainer import *
from app.schemas.trainer import (
    Trainer,
    TrainerBase,
    TrainerCreate,
    TrainerInDBBase,
    TrainerResponse,
    TrainerUpdate,
)
