"""Create all initial tables with updated client model

Revision ID: 44f041826fcd
Revises: fe189b3c1124
Create Date: 2025-09-08 23:07:40.834602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f041826fcd'
down_revision: Union[str, None] = 'fe189b3c1124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('pin', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'clients', ['pin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'pin')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
